### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#425]
Mystic's Monstrosity Lite 1.12.2
- [x] Debug Tick dynamics by makking a fork of tick dynamic
- [x] Maybe change Entity Chunk Cramming fix for Lag'B'Gon Revived

Biggess Pack Cat Edition 1.7.10
- [x] Fix ceramic jar making fps lags by making a fork of zelda sword skills(don't forget to reenabling ceramic jar from worldgen when fixed)
- [x] Try reducing asm errors
- [x] Try reducing logs errors
- [x] Try reducing cascading worldgen
